name: 'Pull Request Reminder'
description: 'Send slack messages to remind reviewing pull requests.'
inputs:
  webhook-url:
    description: 'Slack Webhook URL'
    required: true
  github-slack-map:
    description: 'Map GitHub username to Slack member ID. ex: "spotlight21c:UBCDEFGHI,DavideViolante:UABCDEFGH"'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
